In [1]:
pip install PyDrive


In [2]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


In [3]:

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)


In [4]:
downloaded = drive.CreateFile({'id':"1--vWWO4rrJQjr3Xei2JwnD709dTDQKRS"})   # replace the id with id of file you want to access
downloaded.GetContentFile('file_1.hdf5') 

In [24]:
import h5py
import tensorflow as tf
import scipy.signal

In [13]:
def get_data(data_file):
    
    f = h5py.File(data_file, 'r')
    H_Re = f['H_Re'][:] #shape (sample size, 56, 924, 5)
    H_Im = f['H_Im'][:] #shape (sample size, 56, 924, 5)
    SNR = f['SNR'][:] #shape (sample size, 56, 5)
    Pos = f['Pos'][:] #shape(sample size, 3)
    f.close()
            
    return H_Re, H_Im, SNR, Pos 

In [14]:
H_Re, H_Im, SNR, Pos = get_data('file_1.hdf5')

In [15]:
print("H_Re is of shape {}".format(H_Re.shape))
print("H_Im is of shape {}".format(H_Im.shape))
print("SNR is of shape {}".format(SNR.shape))
print("Pos is of shape {}".format(Pos.shape))

H_Re is of shape (512, 56, 924, 5)
H_Im is of shape (512, 56, 924, 5)
SNR is of shape (512, 56, 5)
Pos is of shape (512, 3)


In [19]:
data1 = tf.constant(H_Re)
data2 = tf.constant(H_Im)
data = tf.math.sqrt(tf.add(tf.math.square(data1), tf.math.square(data2)))

In [20]:
print("Shape of data is {}".format(data.shape))

Shape of data is (512, 56, 924, 5)


In [23]:
data[1][1][1]


<tf.Tensor: shape=(5,), dtype=float16, numpy=array([0.1969, 0.1945, 0.2024, 0.213 , 0.2192], dtype=float16)>

In [27]:
filtered_data = scipy.signal.medfilt(data,[1,1,1,5])

In [28]:
filtered_data[1][1][1]

array([0.19445801, 0.19689941, 0.20239258, 0.20239258, 0.20239258])

In [29]:
scipy.signal.medfilt([12,8,4,9,6],5)

array([4., 8., 8., 6., 4.])

In [30]:
print("Shape of data is {}".format(filtered_data.shape))

Shape of data is (512, 56, 924, 5)
